<AbogadosScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 30
        spacing: 20

        canvas.before:
            Color:
                rgba: 0.07, 0.08, 0.1, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Seleccionar Abogado"
            font_size: 26
            color: 1,1,1,1

        Button:
            text: "Dr. Pérez - Civil"
        Button:
            text: "Dra. Gómez - Penal"