<DashboardScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10

        Label:
            text: "Dashboard"

        Button:
            text: "Nueva Consulta"
            on_release: root.nueva_consulta()

        Button:
            text: "Historial"
            on_release: root.ver_historial()

        Button:
            text: "Mi Perfil"
            on_release: app.root.current = "perfil"