<RegisterScreen>:
    BoxLayout:
        orientation: "vertical"

        TextInput:
            id: username
            hint_text: "Nombre"

        TextInput:
            id: email
            hint_text: "Email"

        TextInput:
            id: password
            hint_text: "Password"
            password: True

        Button:
            text: "Registrarse"
            on_release: root.register()

        Button:
            text: "Volver"
            on_release: root.go_back()